server:
  port: 9000

kakao:
  client-id: "eb75beb1fefad3d0458692af0dd6617f"
  redirect-uri: "http://localhost:9000/auth/kakao/callback"
  token-uri: "https://kauth.kakao.com/oauth/token"
  user-info-uri: "https://kapi.kakao.com/v2/user/me"

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/practice
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: memory3at@gmail.com
    password: axyv ulvc lxdc rhmg   # ← 여기 앱 비밀번호 입력!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
