server:
  port: 9000

kakao:
  client-id: "eb75beb1fefad3d0458692af0dd6617f"
  redirect-uri: "http://localhost:9000/auth/kakao/callback"
  token-uri: "https://kauth.kakao.com/oauth/token"
  user-info-uri: "https://kapi.kakao.com/v2/user/me"

spring:
  data:
    redis:
      host: redis.memoryeat.com # ğŸŸ¡ Redis ì„œë²„ ìœ„ì¹˜ (í˜„ì¬ëŠ” ë‚´ PC)
      port: 6379      # ğŸ”µ Redis ê¸°ë³¸ í¬íŠ¸

  datasource:
    url: jdbc:mariadb://memoryeat.com:3306/practice
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: memory3at@gmail.com
    password: axyv ulvc lxdc rhmg   # â† ì—¬ê¸° ì•± ë¹„ë°€ë²ˆí˜¸ ì…ë ¥!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cors:
    allowed-origins:
      - https://memoryeat.com
      - https://www.memoryeat.com